CREATE DATABASE GameStore507;
USE GameStore507;
CREATE TABLE users (
   user_id INT AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   last_name VARCHAR(100) NOT NULL,
   profile_image VARCHAR(255),
   email VARCHAR(150) NOT NULL UNIQUE,
   province VARCHAR(100),
   user_type ENUM('cliente', 'administrador') NOT NULL,
   password VARCHAR(255) NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE products (
   id INT AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   category VARCHAR(100),
   brand VARCHAR(100),
   model VARCHAR(100),
   specs1 VARCHAR(255),
   specs2 VARCHAR(255),
   specs3 VARCHAR(255),
   price DECIMAL(10, 2) NOT NULL,
   stock INT DEFAULT 100,
   description TEXT NOT NULL,
   image VARCHAR(255),
   image1 VARCHAR(255),
   image2 VARCHAR(255),
   image3 VARCHAR(255),
   image4 VARCHAR(255),
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
USE GameStore507;
SHOW TABLES;
SELECT * FROM Users;
SELECT * FROM Products;
SHOW CREATE TABLE products;
ALTER TABLE products CHANGE id id INT NOT NULL AUTO_INCREMENT;
SELECT id, name, price FROM Products;
SELECT id, name, price FROM Products;
SHOW CREATE TABLE Users;
ALTER TABLE Users MODIFY COLUMN user_id BIGINT NOT NULL AUTO_INCREMENT;
SELECT * FROM Products WHERE category = 'computadoras';
CREATE TABLE Carts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    status ENUM('active', 'purchased') DEFAULT 'active',
    total DECIMAL(10, 2) DEFAULT 0.0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id)
);
ALTER TABLE Users
ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY;
DESCRIBE products;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS product;
DESCRIBE products;
ALTER TABLE carts DROP FOREIGN KEY carts_ibfk_2; 
DROP TABLE IF EXISTS carts; 
DROP TABLE IF EXISTS products; 
DROP TABLE IF EXISTS users; 
CREATE TABLE carts (
    cart_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);
SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE users MODIFY COLUMN user_id BIGINT AUTO_INCREMENT;
ALTER TABLE Carts MODIFY COLUMN user_id BIGINT;
ALTER TABLE Carts DROP FOREIGN KEY carts_ibfk_1;
ALTER TABLE Carts ADD CONSTRAINT carts_ibfk_1 FOREIGN KEY (user_id) REFERENCES Users(user_id);
SET FOREIGN_KEY_CHECKS = 1;
ALTER TABLE products AUTO_INCREMENT = 1;  
DESCRIBE carts;
ALTER TABLE carts 
CHANGE created_at createdAt DATETIME,
CHANGE updated_at updatedAt DATETIME;
SELECT * FROM carts WHERE user_id = 1727943383053;
